# Start with a base image containing Java runtime
FROM java:8

# Add a volume pointing to /tmp
VOLUME /tmp

# Make port 8080 available to the world outside this container
EXPOSE 8080

# The application's jar file
#ARG JAR_FILE=target/employee_management.jar
#ARG JAR_FILE=/var/lib/jenkins/workspace/employee_management_Proc/employee_management/target/employee_management.jar
# Add the application's jar to the container  
#COPY ${JAR_FILE} /employee_management.jar


ADD target/employee_management.jar employee_management.jar

ADD /var/lib/jenkins/workspace/employee_management_Proc/employee_management/target/docker/employee_management.jar /var/lib/docker/tmp/docker-builder252932808/target/employee_management.jar
# Run the jar file  
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/employee_management.jar"]   