# Start with a base image containing Java runtime
FROM java:8

# Add a volume pointing to /tmp
VOLUME /tmp

# Make port 8080 available to the world outside this container
EXPOSE 8080

# The application's jar file
ARG JAR_FILE=target/employee_management.jar

# Add the application's jar to the container  
ADD ${JAR_FILE} /var/lib/docker/tmp/docker-builder944320173/target/employee_management.jar

# Run the jar file  
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/employee_management.jar"]   